# Generated by Django 3.1 on 2020-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200428_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
