# Generated by Django 3.1 on 2020-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201008_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='color_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
