# Generated by Django 3.1 on 2020-10-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_achievements_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='color_code',
            field=models.CharField(blank=True, default='#00000', max_length=100),
        ),
    ]
