# Generated by Django 3.1 on 2020-10-09 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20201009_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name_plural': 'Achievements'},
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='user',
        ),
        migrations.AddField(
            model_name='achievements',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
