# Generated by Django 3.1 on 2020-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201009_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_intern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
