# Generated by Django 3.1 on 2020-10-09 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_auto_20201009_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('q1', models.CharField(max_length=100)),
                ('q2', models.CharField(max_length=100)),
                ('q3', models.CharField(max_length=100)),
                ('q4', models.CharField(max_length=100)),
                ('q5', models.CharField(max_length=100)),
                ('q6', models.CharField(max_length=100)),
                ('q7', models.CharField(max_length=100)),
                ('q8', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
