# Generated by Django 3.1 on 2020-11-11 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='EventWeeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.CharField(max_length=10)),
                ('event_id', models.CharField(default='nav-week-WeekNumber-tab', max_length=100)),
                ('href', models.CharField(default='#nav-week-Weeknumber', max_length=100)),
                ('aria_controls', models.CharField(default='nav-week-WeekNumber', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Event Weeks',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='This is the default text, for more click the title', max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagelink', models.CharField(default='https://res.cloudinary.com/skaetch/image/upload/v1602166969/skaetch/assets/img/blog/single_blog_4_jsrgae.png', max_length=1000)),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_heading', models.CharField(default='Skaetch And Build', max_length=100)),
                ('activity', models.CharField(default='Skaetch And Build', max_length=1000)),
                ('activity_time', models.DateField(default=django.utils.timezone.now)),
                ('detail_point1', models.CharField(default='Skaetch And Build', max_length=1000)),
                ('detail_point2', models.CharField(default='Skaetch And Build', max_length=1000)),
                ('detail_point3', models.CharField(default='Skaetch And Build', max_length=1000)),
                ('event_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.eventweeks')),
            ],
            options={
                'verbose_name_plural': 'Event Details',
            },
        ),
    ]
