# Generated by Django 3.1 on 2020-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201007_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='This is the default text, for more click the title', max_length=100),
        ),
    ]
