# Generated by Django 3.1 on 2020-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201007_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWeeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10)),
            ],
        ),
    ]
