# Generated by Django 3.1 on 2020-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_eventweeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventweeks',
            name='aria_controls',
            field=models.CharField(default='nav-week-<django.db.models.fields.CharField>', max_length=10),
        ),
        migrations.AddField(
            model_name='eventweeks',
            name='event_id',
            field=models.CharField(default='nav-week-<django.db.models.fields.CharField>-tab', max_length=10),
        ),
        migrations.AddField(
            model_name='eventweeks',
            name='href',
            field=models.CharField(default='#nav-week-<django.db.models.fields.CharField>', max_length=10),
        ),
    ]
