# Generated by Django 3.1 on 2020-10-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201008_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventweeks',
            old_name='week',
            new_name='week_number',
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='aria_controls',
            field=models.CharField(default='nav-week-number', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='event_id',
            field=models.CharField(default='nav-week-number-tab', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='href',
            field=models.CharField(default='#nav-week-number', max_length=10),
        ),
    ]
