# Generated by Django 3.1 on 2020-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201008_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventweeks',
            name='aria_controls',
            field=models.CharField(default='nav-week-number', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='event_id',
            field=models.CharField(default='nav-week-number-tab', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='href',
            field=models.CharField(default='#nav-week-number', max_length=100),
        ),
    ]
