# Generated by Django 3.1 on 2020-10-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201008_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventweeks',
            options={'verbose_name_plural': 'Event Weeks'},
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('event_heading', models.CharField(default='Skaetch And Build', max_length=100)),
                ('event_description', models.CharField(default='Skaetch And Build', max_length=1000)),
                ('event_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.eventweeks')),
            ],
            options={
                'verbose_name_plural': 'Event Details',
            },
        ),
    ]
