# Generated by Django 3.1 on 2020-10-08 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201008_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetails',
            old_name='event_description',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='event_date',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='activity_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 12, 10, 10, 533132, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='detail_point1',
            field=models.CharField(default='Skaetch And Build', max_length=1000),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='detail_point2',
            field=models.CharField(default='Skaetch And Build', max_length=1000),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='detail_point3',
            field=models.CharField(default='Skaetch And Build', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_week',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.eventweeks'),
        ),
    ]
