# Generated by Django 3.1 on 2020-10-08 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201008_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='activity_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 12, 38, 22, 865638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='aria_controls',
            field=models.CharField(default='nav-week-week_number', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='event_id',
            field=models.CharField(default='nav-week-week_number-tab', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='href',
            field=models.CharField(default='#nav-week-week_number', max_length=100),
        ),
    ]
