# Generated by Django 3.1 on 2020-10-08 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201008_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='activity_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 12, 39, 22, 368566, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='aria_controls',
            field=models.CharField(default='nav-week-WeekNumber', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='event_id',
            field=models.CharField(default='nav-week-WeekNumber-tab', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventweeks',
            name='href',
            field=models.CharField(default='#nav-week-Weeknumber', max_length=100),
        ),
    ]
