# Generated by Django 3.1 on 2020-10-08 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201008_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.CharField(default='https://res.cloudinary.com/skaetch/image/upload/v1602166969/skaetch/assets/img/blog/single_blog_4_jsrgae.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='activity_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 14, 35, 15, 850629, tzinfo=utc)),
        ),
    ]
