# Generated by Django 3.1 on 2020-10-09 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20201009_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='activity_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 0, 16, 29, 948735, tzinfo=utc)),
        ),
    ]
