# Generated by Django 3.1 on 2020-10-09 01:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20201009_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='activity_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 1, 11, 30, 16682, tzinfo=utc)),
        ),
    ]
