# Generated by Django 3.1 on 2020-10-13 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20201009_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='activity_time',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 15, 29, 35, 997652, tzinfo=utc)),
        ),
    ]
