# Generated by Django 3.1 on 2020-10-09 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20201009_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='activity_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
