# Generated by Django 3.1 on 2020-10-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20201013_1631'),
        ('home', '0028_auto_20201009_1143'),
    ]

    operations = [
    ]
